language: node_js
node_js:
- lts/*
- stable
deploy:
  provider: npm
  email: nathan@nfriedly.com
  api_key:
    secure: CE0+zKQeuTurXg4g7e+Cd2cHIr1K1OomK+lTY2CG7OCXOMQs24WWkZSMySRnFWbWFaXYaVWLgZXFVqAD28Llnpkmn8at2N5fjjfcMtEACpM1eP1OF1kLKPonyNMyqg9lT2NMm0OUIEHa1hHWOua6B3nt95bMaHwNkvlWHGaSpsA=
  on:
    tags: true
    repo: nfriedly/approximate-number
